dataset: yelp
output_path: results
load_path: null
data_path: data

seed: 256

evaluation_budget: 40
max_budget: 30
min_budget: 3
n_trials: 50
optimizer: ifbo  # use rl_freeze_thaw for the PPO Freeze--Thaw scheduler

approach: sequence-dl
num_workers: 2 # TODO: I don't think this is being properly used
max_num_rows: 50000

max_trainers_in_memory: 2
log_level: DEBUG
use_random_selection: false
ifbo_greedy_candidate_selection: false