dataset: imdb
output_path: results
load_path: null
data_path: data

seed: 42

evaluation_budget: 10
max_budget: 20
min_budget: 5
n_trials: 10
optimizer: smac  # use rl_freeze_thaw for the PPO Freeze--Thaw scheduler

approach: sequence-dl
num_workers: 2
max_num_rows: 20000

max_trainers_in_memory: 2